### ISSUE TITLE
Missing imports/pto_import.owl

### ISSUE THREAD

**Issue by safisher** [GenEpiO/genepio#13]
The ontology "genepio.owl" includes "GENEPIO/imports/pto_import.owl" which doesn't actually exist.

**Comment by Public-Health-Bioinformatics** [comment]
Thanks for letting us know - this will be fixed shortly.  It is a typo - the "t" should be a "c".  Also the pco_import.owl file has the same typo fixed in the import file; that has now been updated.

**Comment by Public-Health-Bioinformatics** [comment]
This should be resolved now.
