### ISSUE TITLE
Use of 'aligned with' relation to map geopolitical areas to planetary surface

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [GenEpiO/genepio#17]
Relation Ontology has an 'aligned with' relation that should enable mapping named geopolitical areas to planetary surface areas.  How exactly could polygon information be linked to?  Some consider storage of GIS info outside the purview of an ontology since it can't be reasoned over very well (reasoner may show benefits of statements of country adjacency though). However, by having this surface polygon information associated with a geo-name, as an annotation say, it would make it very easy to pass this info on to programs that could use it, via SPARQL, etc.

**Comment by ddooley** [comment]
Closing this now, in favour of using other resources for this (e.g. wikidata, geonames).
