### ISSUE TITLE
"Specimen from organism" is a material entity but has GEEM spec components.

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [GenEpiO/genepio#18]
An information content entity is required instead. Probably need another term, like "organic specimen material", with the following axioms.

'has component' max 1 (categorical and (specifies some 'subject anatomical site'))
'has component' max 1 (categorical and (specifies some 'subject body product'))

**Comment by ddooley** [comment]
Fixed. Now there is a separate "specimen from organism specification" entity.
