### ISSUE TITLE
Use of Gazetteer for geolocation

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [GenEpiO/genepio#2]
I'm going to make the underlying geography database for selecting countries, states/provinces, and cities to be the GAZETTEER ontology.  Although it doesn't have the US county granularity that GEO does, it does have great coverage - and lookup capability - for cities and regions in the rest of the world.  

Several people have expressed a desire to see GenEpiO offer regional obfuscation of location data, so that say Canada can be split into western Canada, central Canada, eastern, etc; and the US into western US, central, eastern.  The idea that state/province/territory level governments can merge their data with each other and thereby honour de-identification commitments.  I'll see if Gazetteer has an interest in ontologizing such groupings.

**Comment by Public-Health-Bioinformatics** [comment]
One possibility is to make use of Canadian Gazetteer census regions which are often agglomerations of municipal regions.  This could allow prairie provinces to de-identify city level data for example.

**Comment by Public-Health-Bioinformatics** [comment]
Good progress here - have national and provincial and municipal details in for a number of countries like Australia, New Zealand, Canada, Britain, Ireland, China and Korea. A technical OntoFox or GAZETTEER issue is preventing US States from being imported though; looking into this.

**Comment by Public-Health-Bioinformatics** [comment]
There is one discrepancy in Gazetteer right now: It had adopted the practice of having owl:NamedIndividual with same id's as owl:Class for a number of items (punning), but not for states in the USA; a second issue is that it appears OntoFox doesn't allow exploration of hierarchies other than via subClassOf relation.  Most countries and regions are related by "located in", which means at moment one must spell them out by country/region id in OntoFox to get them imported.  I've sent out requests for more info on both these issues to see what the future holds.

**Comment by ddooley** [comment]
GAZ issues are being resolved at: https://github.com/EnvironmentOntology/gaz/issues/20
