### ISSUE TITLE
Normalising NCIT ids to be more interoperable with other OBO ontologies?

### ISSUE THREAD

**Issue by matentzn** [GenEpiO/genepio#21]
GENEPIO is using NCIT identifiers such as:

http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Amniotic_Fluid
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Amniotic_Sac
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C103180
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C107150
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C15958
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C21204
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C66829
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Chorionic_Villus
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Embryonic_Fluid
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Gonad
http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#Iliac_Vein

The usual OBO Ids for these are:
http://purl.obolibrary.org/obo/NCIT_C43816

To make OBO ontologies more interoperable, maybe it makes sense to normalise these to the OBO PURLs?

Note that GENEPIO does not use all the ids above - these are the instances I found across the whole OBO foundry, but some of them come from GENEPIO.

Context: Our grand OBO wide ID normalisation effort.
https://github.com/orgs/OBOFoundry/projects/5

**Comment by ddooley** [comment]
I believe this is resolved now.  GenEpiO only has one remaining EVS purl instance, c66829, and that will be deleted in upcoming release.
