### ISSUE TITLE
Health status datum - for comment

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [GenEpiO/genepio#3]
GenEpiO has a clinical datum called a "health status", imported from the Exposure Ontology, which I have taken the liberty to map to the NCBI BioSample "host_health_state" field (via a hasDbXref annotation), which itself currently appears to be free-text, i.e. no NCBI directive to draw selections from an ontology.  So the task here is to form a decent "health status" categorical input.  So far I've organized it in a little hierarchy, drawing from PATO, GO, SIO, OAE, NDF-RT, CVDO, and new GENEPIO terms.  I've tried to state equivalencies.  

Do these sub-categories work well?  
Are there finer distinctions we should be making?
Note GenEpiO's narrower meaning of "life status" in comparison to "health status".

[update] I see Wikipedia has a number of [medical state](https://en.wikipedia.org/wiki/Medical_state) distinctions, based on national standards and synonyms, that we could consider.

Should we distinguish between health status as a point in time observable, e.g. "undetermined/good/fair/serious/critical/dead" vs. health status pattern from a case duration perspective - which could involve terms like recurring, recovering, improving, worsening - i.e. trends?

<img width="909" alt="screen shot 2016-09-02 at 9 58 24 am" src="https://cloud.githubusercontent.com/assets/10779910/18211722/fd5679e0-70f3-11e6-9834-d8d4e863c2f0.png">

**Comment by Public-Health-Bioinformatics** [comment]
Semantically it looks like there are three separate observations currently being described in "health status" above, that probably need to be separated out.  

- "health status" as an ordinal value describing the state of health for a given case at a particular point in time.  Adding the ordinal relation between values (...,good,fair,serious,...) adds some statistical power.
- "health status trend" or as Wikipedia puts it "short term prognosis" of a given case.
- "health status history" (or alt. term?) a description of long term characteristics of health pertinent to the case at hand.

**Comment by cmrn-rhi** [comment]
Does this issue still need to remain open?

**Comment by ddooley** [comment]
It looks like this can be closed.  Latest view of "health status" is:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/4000582/170112618-f3b2783e-9644-4813-85fc-58aecadb5388.png">

As we turn to separating out picklist content via linkml we'll probably circle back to this content.
