### ISSUE TITLE
What is the status of GENEPIO:0002094, specimen (sample?) collection device

### ISSUE THREAD

**Issue by turbomam** [GenEpiO/genepio#36]
http://purl.obolibrary.org/obo/GENEPIO_0002094  is still mentioned in MIxS's notes about their`samp_collec_device` term

But that ID doesn't resolve in OntoBee anymore:

http://www.ontobee.org/ontology/GENEPIO?iri=http://purl.obolibrary.org/obo/GENEPIO_0002094

Although it does resolve in OLS

https://www.ebi.ac.uk/ols/ontologies/genepio/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENEPIO_0002094

**Comment by turbomam** [comment]
Thanks. so you consider [GENEPIO:0002094](http://www.ontobee.org/ontology/GENEPIO?iri=http://purl.obolibrary.org/obo/GENEPIO_0002094) a live, stable term?

What is its preferred label now?

**Comment by cmrn-rhi** [comment]
Related issue: https://github.com/obi-ontology/obi/issues/1194

**Comment by ddooley** [comment]
@turbomam - Mark, can we have MIxS switch to specimen collection device?

**Comment by ddooley** [comment]
@turboman GenEpiO term is deprecated in favour of OBI one.  I'm closing this now, but I am curious if MIxS switch to the OBI term?
