### ISSUE TITLE
Design of GenEpiO interface to 3rd party databases like NCBI BioSample, for comment

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [GenEpiO/genepio#4]
To facilitate data exchange between the ideally generic epidemiological, laboratory and other biomedical concepts that GenEpiO contains, and the specific entities that projects like NCBI BioSample use to import or export data.  For GenEpiO to operate as a clearinghouse of field and entity specifications, it needs to record the specifications of 3rd party databases on a field-to-field basis.

Our current approach now involves documenting 3rd party field information using the **hasDbXref** database cross reference relation which is commonly used to point to specific identifiers in 3rd party databases, e.g. "'Coregonus reighardi' hasDbXref ITIS:161947".  This can also be used to point to metadata - e.g. field names.  To organize this explicitly we have added a "centrally registered identifier symbol" -> "**source database**", which is a place to list all the database acronyms used as prefixes in the hasDbXref.  Details of common taxonomic and geographic cross-reference databases are now listed here, for example Geonames, SNOMEDCT, ITIS, FAO ASFIS, etc.  

<img width="506" alt="screen shot 2016-09-14 at 10 16 36 am" src="https://cloud.githubusercontent.com/assets/10779910/18522311/669a1096-7a64-11e6-9411-222804f1b6a1.png">

Cross-references to other OBOFoundry ontology terms would likely be handled more directly via relations or equivalencies. There are a number of more complex issues to address (date format conversion and age to bucketed age range fields for example) which will require annotations on the hasDbXref annotations themselves.

**Comment by ddooley** [comment]
The source database list remains useful - and instances of each class can document versions of the given database.  However, we now use a "field specification" class to document details of each field in a given 3rd party table, such as the example PulseNet specification below.

![image](https://user-images.githubusercontent.com/4000582/67798558-f8c4aa80-fa40-11e9-92cc-155ae51e0d88.png)

The hasDbXref relation is no longer used to point to these field specs, but instead, specification fields reference the field instances:

![image](https://user-images.githubusercontent.com/4000582/67798790-6cff4e00-fa41-11e9-97bc-9d6334ac714f.png)
