### ISSUE TITLE
There are 1090 unsatisfiable classes in GenEpiO

### ISSUE THREAD

**Issue by dillerm** [GenEpiO/genepio#48]
I ran the HermiT reasoner on the latest release of GenEpiO and it identified 1090 classes as being unsatisfiable (see attached Excel file). For example, I believe the first class in the list--'cartesian coordinate system' (STATO:0000009)--is unsatisfiable because its parent class--'coordinate system' (STATO:0000010)--is asserted to be a subclass of 'information content entity' (a generically dependent continuant) and 'n-dimensional concept' (an independent continuant). STATO:0000010 is also unsatisfiable and included in the list.

[unsatisfiable_classes_genepio.xlsx](https://github.com/GenEpiO/genepio/files/9997955/unsatisfiable_classes_genepio.xlsx)

**Comment by ddooley** [comment]
Sorry for delay in response.  Thanks for reporting this.  I did run a reasoner on it and found some malformed data types which have now been fixed.  Now, although Hermit didn't return that list of unsatisfiable classes that you had (Did you use the Github version of genepio.owl?) I did discover that our import of EFO terms was causing information content entity and other high-level BFO terms to be positioned under their  'experimental factor' class.  I've adjusted the EFO import to fix this.  Could you let me know if your run of the reasoner still faults the GitHub  [/genepio.owl ](https://github.com/GenEpiO/genepio/blob/master/genepio.owl) file?

**Comment by dillerm** [comment]
This was for what looks to be the previous release (2021-05-24). Everything looks good on my end.
