### ISSUE TITLE
Age of patient or animal as host

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [GenEpiO/genepio#5]
Recording age rather than birth date can be a handy way of de-personalizing information as well as delivering a simple age bracket summary.  Do the following datums sound like they will cover our need for types of organism age?
- The Ontology for Biomedical Investigations has an "**age measurement datum**" which is a broad category for the age of some organism achieved by measurement - e.g. by calculating the duration by tree rings or birth date or conception date.
- For epidemiology we're definitely interested in the OBI '**age since birth measurement datum**' subclass.  This covers both patients who have come down with an illness and people who may or may not be hosts.  
- Then GenEpiO introduces an intermediary "**host age**" for those who appear to be affected by a pathogen.  To fit the OBI paradigm, I've defined host age as "the age of an organism bearing a host role during some process or event".  
- Finally, as called for, by the NCBI and PulseNet data submission cases (and others) we have "**host age at date of sampling**"; here the sample is often the focus, and ideally relevant host information like age is captured.

Note though that age isn't necessarily measured in years.  In some studies, about infants for example, age may be measured in hours, days, weeks, or months.  Secondly, we usually need to have a record of **when** an organism was stated to have a certain age. (A date is usually needed for any other datum collected about an organism too.)

**Comment by ddooley** [comment]
We have continued discussion on this topic at: https://github.com/obi-ontology/obi/issues/1041
