### ISSUE TITLE
Some of the pha4ge owl template robot output is syntactically wrong.

### ISSUE THREAD

**Issue by ddooley** [GenEpiO/genepio#50]
The data type wasn't successfully changed to xsd:integer:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/4000582/203415776-6be5f6d9-eb0e-4303-83a0-830789c76e42.png">

also:  <linkml:minimum_value rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">0&quot;</linkml:minimum_value>

manually fixed but robot regeneration will overwrite this.

**Comment by cmrn-rhi** [comment]
We are going to archive these tables and transition to different specification ROBOT tables that don't model the LinkML schema directly so this will no longer be an issue on the next release.
