### ISSUE TITLE
genepio not loading on OLS

### ISSUE THREAD

**Issue by henrietteharmse** [GenEpiO/genepio#58]
See issue [https://github.com/EBISPOT/ols4/issues/304#issuecomment-1647662724](https://github.com/EBISPOT/ols4/issues/304#issuecomment-1647662724)

**Comment by cmrn-rhi** [comment]
@cmrn-rhi identified the likely ROBOT table culprits. Have fixed them and intend to rerun next week.

**Comment by ddooley** [comment]
This is solved for now!
