### ISSUE TITLE
gitignore additions?

### ISSUE THREAD

**Issue by cmrn-rhi** [GenEpiO/genepio#69]
The src/ontology/genepio-full.owl and src/ontology/genepio.owl files don't really need to be included in the pull request since they are byproducts of build process.  You could leave them in this time since they are already there but in future they don't have to be included.  We could put them in the gitignore file I guess.

_Originally posted by @ddooley in https://github.com/GenEpiO/genepio/pull/68#pullrequestreview-1680748964_

@ddooley so just confirming there will never be a case when we need these files? Because if s, yes I agree that they should be added to gitignore.

**Comment by ddooley** [comment]
Yes, that's right, they are intermediary products that don't get referenced by anyone/thing.  genepio.owl gets copied up to root on "make prepare_release" or whatever the latest ODK release command is.

**Comment by cmrn-rhi** [comment]
Thank you. I'll add them to the gitignore on my next branch.
